// Utility to get icon components by name
import {
  IconDashboard,
  IconAI,
  IconModules,
  IconSettings,
  IconSearch,
  IconBell,
  IconInterface,
  IconSystemAdmin,
  IconTheme,
  IconLayout,
  IconDisplay,
  IconNavigation,
  IconUser,
  IconLogout,
  IconAPI,
  IconChess,
  IconShield,
  IconBriefcase,
  IconLanguage,
  IconLibrary,
  IconInUse,
  IconIntegrated,
  IconOpenSource,
  IconCore,
  IconTools,
  IconCategory,
  IconExternalLink,
  IconEye,
  IconDeveloper,
  IconDatabase,
  IconServer,
  IconFolder,
  IconFile,
  IconCheckCircle,
  IconXCircle,
  IconPlay,
  IconStop,
  IconPackage,
  IconStatus,
  IconUpload,
  IconLink,
  IconGithub,
  IconTable,
  IconCopy,
  IconMaximize,
  IconMinimize,
} from '@/components/Icons'

export const iconMap: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  IconDashboard,
  IconAI,
  IconModules,
  IconSettings,
  IconSearch,
  IconBell,
  IconInterface,
  IconSystemAdmin,
  IconTheme,
  IconLayout,
  IconDisplay,
  IconNavigation,
  IconUser,
  IconLogout,
  IconAPI,
  IconChess,
  IconShield,
  IconBriefcase,
  IconLanguage,
  IconLibrary,
  IconInUse,
  IconIntegrated,
  IconOpenSource,
  IconCore,
  IconTools,
  IconCategory,
  IconExternalLink,
  IconEye,
  IconDeveloper,
  IconDatabase,
  IconServer,
  IconFolder,
  IconFile,
  IconCheckCircle,
  IconXCircle,
  IconPlay,
  IconStop,
  IconPackage,
  IconStatus,
  IconUpload,
  IconLink,
  IconGithub,
  IconTable,
  IconCopy,
  IconMaximize,
  IconMinimize,
}

export function getIcon(iconName: string): React.ComponentType<React.SVGProps<SVGSVGElement>> {
  if (!iconName) return IconDashboard
  return iconMap[iconName] || IconDashboard
}

